#############################################
# DB Subnet Group -- private subnets only
#############################################
resource "aws_db_subnet_group" "this" {
  name       = "${var.project_name}-db-subnet-group"
  subnet_ids = var.private_subnet_ids

  tags = {
    Name = "${var.project_name}-db-subnet-group"
  }
}

#############################################
# Master password -- generated by Terraform (not hardcoded), stored in
# Secrets Manager. Never appears in a task definition; only the composed
# per-service DATABASE_URL secrets below do, and those are injected into
# ECS tasks via the "secrets" block (resolved at container start, not baked
# into the task definition JSON).
#############################################
resource "random_password" "master" {
  length  = 32
  special = false # keep it URL-safe since it's embedded in a postgresql:// connection string
}

resource "aws_secretsmanager_secret" "rds_master" {
  name = "${var.project_name}/rds/master-credentials"

  tags = {
    Name = "${var.project_name}-rds-master-credentials"
  }
}

resource "aws_secretsmanager_secret_version" "rds_master" {
  secret_id = aws_secretsmanager_secret.rds_master.id
  secret_string = jsonencode({
    username = var.master_username
    password = random_password.master.result
    host     = aws_db_instance.this.address
    port     = aws_db_instance.this.port
  })
}

#############################################
# RDS PostgreSQL instance
#############################################
resource "aws_db_instance" "this" {
  identifier     = "${var.project_name}-db"
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage = var.allocated_storage
  storage_type      = "gp3"
  storage_encrypted = true

  db_name = "postgres" # master/admin database only; each service's own DB
  # (userdb/blogdb/categorydb/notificationdb) is
  # created by db-init/01-create-databases.sh's SQL,
  # run once against this endpoint -- see README /
  # IMPLEMENTATION_STATUS "EXACT NEXT STEP".
  username = var.master_username
  password = random_password.master.result

  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.security_group_id]
  publicly_accessible    = false

  multi_az                  = var.multi_az
  backup_retention_period   = var.backup_retention_period
  skip_final_snapshot       = var.skip_final_snapshot
  final_snapshot_identifier = var.skip_final_snapshot ? null : "${var.project_name}-db-final-snapshot"

  deletion_protection = false

  tags = {
    Name = "${var.project_name}-db"
  }
}

#############################################
# Per-service DATABASE_URL secrets -- one full connection string per
# microservice database, composed here (Terraform has the password) so the
# app's existing single-env-var DATABASE_URL pattern (see docker-compose.yml)
# needs no code changes. Injected into each service's task definition via
# the ECS "secrets" block.
#############################################
resource "aws_secretsmanager_secret" "database_url" {
  for_each = toset(var.service_database_names)
  name     = "${var.project_name}/database-url/${each.value}"

  tags = {
    Name = "${var.project_name}-database-url-${each.value}"
  }
}

resource "aws_secretsmanager_secret_version" "database_url" {
  for_each      = aws_secretsmanager_secret.database_url
  secret_id     = each.value.id
  secret_string = "postgresql+psycopg2://${var.master_username}:${random_password.master.result}@${aws_db_instance.this.address}:${aws_db_instance.this.port}/${each.key}"
}
