#############################################
# Root module -- Stage 2 AWS infrastructure (ECS Fargate architecture)
#
# Supersedes the Stage 1 EC2 + Docker-run deploy path documented in
# PROJECT_AUDIT.md section 6/9. The old ec2/ and s3/ modules are left on
# disk (untouched) but are no longer instantiated here -- see
# IMPLEMENTATION_STATUS.md.
#############################################

data "aws_availability_zones" "available" {
  state = "available"
}

locals {
  availability_zones = slice(data.aws_availability_zones.available.names, 0, var.az_count)

  ecr_repo_names = [
    "frontend",
    "gateway",
    "user-service",
    "blog-service",
    "category-service",
    "notification-service",
  ]

  # Container ports opened for self-referencing intra-cluster traffic on the
  # shared ECS tasks security group (frontend's inbound-from-ALB rule on 80
  # is handled separately inside the security_group module).
  container_ports = [80, 8080, 8001, 8002, 8003, 8004]
}

#############################################
# Networking
#############################################
module "vpc" {
  source = "./modules/vpc"

  project_name          = var.project_name
  vpc_cidr              = var.vpc_cidr
  availability_zones    = local.availability_zones
  public_subnet_cidrs   = var.public_subnet_cidrs
  private_subnet_cidrs  = var.private_subnet_cidrs
  enable_nat_gateway    = var.enable_nat_gateway
}

module "security_group" {
  source = "./modules/security_group"

  project_name    = var.project_name
  vpc_id          = module.vpc.vpc_id
  container_ports = local.container_ports
}

#############################################
# ECR
#############################################
module "ecr" {
  source = "./modules/ecr"

  project_name     = var.project_name
  repository_names = local.ecr_repo_names
}

#############################################
# SQS
#############################################
module "sqs" {
  source = "./modules/sqs"

  project_name       = var.project_name
  queue_name         = var.sqs_queue_name
  max_receive_count  = var.sqs_max_receive_count
}

#############################################
# JWT secret -- generated by Terraform, never hardcoded. Shared across
# user/blog/category/notification-service, matching the app's existing
# single-JWT_SECRET design (documented in blog-service/app/security.py).
#############################################
resource "random_password" "jwt_secret" {
  length  = 48
  special = false
}

resource "aws_secretsmanager_secret" "jwt_secret" {
  name = "${var.project_name}/jwt-secret"

  tags = {
    Name = "${var.project_name}-jwt-secret"
  }
}

resource "aws_secretsmanager_secret_version" "jwt_secret" {
  secret_id     = aws_secretsmanager_secret.jwt_secret.id
  secret_string = random_password.jwt_secret.result
}

#############################################
# RDS
#############################################
module "rds" {
  source = "./modules/rds"

  project_name            = var.project_name
  private_subnet_ids      = module.vpc.private_subnet_ids
  security_group_id       = module.security_group.rds_security_group_id
  instance_class           = var.db_instance_class
  allocated_storage       = var.db_allocated_storage
  multi_az                = var.db_multi_az
  master_username          = var.db_master_username
  skip_final_snapshot     = var.db_skip_final_snapshot
  service_database_names  = ["userdb", "blogdb", "categorydb", "notificationdb"]
}

#############################################
# IAM
#############################################
module "iam" {
  source = "./modules/iam"

  project_name = var.project_name
  sqs_queue_arn = module.sqs.queue_arn
  secrets_manager_secret_arns = concat(
    [aws_secretsmanager_secret.jwt_secret.arn],
    values(module.rds.database_url_secret_arns),
  )
}

#############################################
# ECS Cluster + Service Connect namespace
#############################################
module "ecs_cluster" {
  source = "./modules/ecs_cluster"

  project_name = var.project_name
}

#############################################
# ALB
#############################################
module "alb" {
  source = "./modules/alb"

  project_name       = var.project_name
  vpc_id             = module.vpc.vpc_id
  public_subnet_ids  = module.vpc.public_subnet_ids
  security_group_id  = module.security_group.alb_security_group_id
}

#############################################
# ECS Services
#############################################

# -- frontend: nginx + built React/static site; only service behind the ALB.
# Its own nginx.conf already proxies /api/ to http://gateway:8080/api/, which
# Service Connect resolves inside the cluster -- no app changes needed.
module "frontend_service" {
  source = "./modules/ecs_service"

  project_name        = var.project_name
  service_name        = "frontend"
  container_image     = "${module.ecr.repository_urls["frontend"]}:${var.image_tag}"
  container_port      = 80
  cpu                 = var.task_cpu
  memory              = var.task_memory
  desired_count       = var.desired_count
  cluster_id          = module.ecs_cluster.cluster_id
  cluster_name        = module.ecs_cluster.cluster_name
  namespace_arn       = module.ecs_cluster.namespace_arn
  private_subnet_ids  = module.vpc.private_subnet_ids
  security_group_ids  = [module.security_group.ecs_tasks_security_group_id]
  execution_role_arn  = module.iam.ecs_task_execution_role_arn
  target_group_arn    = module.alb.frontend_target_group_arn
  aws_region          = var.aws_region
}

# -- gateway: plain nginx API gateway, internal only (reached by frontend
# over Service Connect as "gateway:8080"), fans out to the 4 microservices.
module "gateway_service" {
  source = "./modules/ecs_service"

  project_name        = var.project_name
  service_name        = "gateway"
  container_image     = "${module.ecr.repository_urls["gateway"]}:${var.image_tag}"
  container_port      = 8080
  cpu                 = var.task_cpu
  memory              = var.task_memory
  desired_count       = var.desired_count
  cluster_id          = module.ecs_cluster.cluster_id
  cluster_name        = module.ecs_cluster.cluster_name
  namespace_arn       = module.ecs_cluster.namespace_arn
  private_subnet_ids  = module.vpc.private_subnet_ids
  security_group_ids  = [module.security_group.ecs_tasks_security_group_id]
  execution_role_arn  = module.iam.ecs_task_execution_role_arn
  aws_region          = var.aws_region

  depends_on = [module.user_service, module.blog_service, module.category_service, module.notification_service]
}

module "user_service" {
  source = "./modules/ecs_service"

  project_name        = var.project_name
  service_name        = "user-service"
  container_image     = "${module.ecr.repository_urls["user-service"]}:${var.image_tag}"
  container_port      = 8001
  cpu                 = var.task_cpu
  memory              = var.task_memory
  desired_count       = var.desired_count
  cluster_id          = module.ecs_cluster.cluster_id
  cluster_name        = module.ecs_cluster.cluster_name
  namespace_arn       = module.ecs_cluster.namespace_arn
  private_subnet_ids  = module.vpc.private_subnet_ids
  security_group_ids  = [module.security_group.ecs_tasks_security_group_id]
  execution_role_arn  = module.iam.ecs_task_execution_role_arn
  task_role_arn       = module.iam.app_task_role_arn
  aws_region          = var.aws_region

  environment = {
    JWT_EXPIRE_MINUTES = tostring(var.jwt_expire_minutes)
    AWS_REGION          = var.aws_region
    SQS_QUEUE_URL       = module.sqs.queue_url
  }

  secrets = {
    DATABASE_URL = module.rds.database_url_secret_arns["userdb"]
    JWT_SECRET   = aws_secretsmanager_secret.jwt_secret.arn
  }
}

module "blog_service" {
  source = "./modules/ecs_service"

  project_name        = var.project_name
  service_name        = "blog-service"
  container_image     = "${module.ecr.repository_urls["blog-service"]}:${var.image_tag}"
  container_port      = 8002
  cpu                 = var.task_cpu
  memory              = var.task_memory
  desired_count       = var.desired_count
  cluster_id          = module.ecs_cluster.cluster_id
  cluster_name        = module.ecs_cluster.cluster_name
  namespace_arn       = module.ecs_cluster.namespace_arn
  private_subnet_ids  = module.vpc.private_subnet_ids
  security_group_ids  = [module.security_group.ecs_tasks_security_group_id]
  execution_role_arn  = module.iam.ecs_task_execution_role_arn
  task_role_arn       = module.iam.app_task_role_arn
  aws_region          = var.aws_region

  environment = {
    AWS_REGION    = var.aws_region
    SQS_QUEUE_URL = module.sqs.queue_url
  }

  secrets = {
    DATABASE_URL = module.rds.database_url_secret_arns["blogdb"]
    JWT_SECRET   = aws_secretsmanager_secret.jwt_secret.arn
  }
}

module "category_service" {
  source = "./modules/ecs_service"

  project_name        = var.project_name
  service_name        = "category-service"
  container_image     = "${module.ecr.repository_urls["category-service"]}:${var.image_tag}"
  container_port      = 8003
  cpu                 = var.task_cpu
  memory              = var.task_memory
  desired_count       = var.desired_count
  cluster_id          = module.ecs_cluster.cluster_id
  cluster_name        = module.ecs_cluster.cluster_name
  namespace_arn       = module.ecs_cluster.namespace_arn
  private_subnet_ids  = module.vpc.private_subnet_ids
  security_group_ids  = [module.security_group.ecs_tasks_security_group_id]
  execution_role_arn  = module.iam.ecs_task_execution_role_arn
  aws_region          = var.aws_region

  secrets = {
    DATABASE_URL = module.rds.database_url_secret_arns["categorydb"]
    JWT_SECRET   = aws_secretsmanager_secret.jwt_secret.arn
  }
}

module "notification_service" {
  source = "./modules/ecs_service"

  project_name        = var.project_name
  service_name        = "notification-service"
  container_image     = "${module.ecr.repository_urls["notification-service"]}:${var.image_tag}"
  container_port      = 8004
  cpu                 = var.task_cpu
  memory              = var.task_memory
  desired_count       = var.desired_count
  cluster_id          = module.ecs_cluster.cluster_id
  cluster_name        = module.ecs_cluster.cluster_name
  namespace_arn       = module.ecs_cluster.namespace_arn
  private_subnet_ids  = module.vpc.private_subnet_ids
  security_group_ids  = [module.security_group.ecs_tasks_security_group_id]
  execution_role_arn  = module.iam.ecs_task_execution_role_arn
  task_role_arn       = module.iam.app_task_role_arn
  aws_region          = var.aws_region

  environment = {
    AWS_REGION            = var.aws_region
    SQS_QUEUE_URL         = module.sqs.queue_url
    SQS_POLL_WAIT_SECONDS = "10"
  }

  secrets = {
    DATABASE_URL = module.rds.database_url_secret_arns["notificationdb"]
    JWT_SECRET   = aws_secretsmanager_secret.jwt_secret.arn
  }
}
