# Copy to terraform.tfvars and adjust for your environment.
# NEVER commit a terraform.tfvars with real account-specific secrets --
# there aren't any expected here (RDS/JWT credentials are generated by
# Terraform into Secrets Manager, not set via variables), but double check
# before committing anyway.

aws_region   = "ap-south-1"
project_name = "devopshub"
environment  = "production"

vpc_cidr             = "10.0.0.0/16"
public_subnet_cidrs  = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs = ["10.0.11.0/24", "10.0.12.0/24"]
az_count             = 2
enable_nat_gateway   = true

image_tag = "latest"

task_cpu      = 256
task_memory   = 512
desired_count = 1

db_instance_class      = "db.t3.micro"
db_allocated_storage   = 20
db_multi_az            = false
db_master_username     = "devopshub"
db_skip_final_snapshot = true

sqs_queue_name         = "notifications"
sqs_max_receive_count  = 5

jwt_expire_minutes = 60
